Tell Zeitwerk to ignore tasks subfolders
Zeitwerk throws errors from the tasks subfolders:
   NameError: wrong constant name

These don't need to be loaded by Zeitwerk (they are not core to the running app, and are loaded by Rake for running as tasks). So rather than rename folders just to make Zeitwerk happy we can have it ignore these.